from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session

app = FastAPI()

# Allow React frontend to access API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],  # React app URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- 1. POSTGRESQL DATABASE CONFIGURATION ---
# Replace with your actual Postgres credentials: postgresql://username:password@host:port/database_name
DATABASE_URL = "postgresql+psycopg://postgres:password@localhost:5432/todo_db"

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


# --- 2. SQLALCHEMY MODEL (Database Table) ---
class DBTask(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    text = Column(String, nullable=False)
    status = Column(String, default="pending")
    priority = Column(String, default="moderate")


# Create tables in database automatically if they don't exist
Base.metadata.create_all(bind=engine)


# --- 3. PYDANTIC SCHEMAS (Data Validation & Serialization) ---
class TaskBase(BaseModel):
    text: str
    status: str
    priority: str

class TaskCreate(TaskBase):
    pass  # Used when creating a new task (id is not sent by client, auto-generated by DB)

class TaskResponse(TaskBase):
    id: int  # Used when sending data back to client (includes id)

    class Config:
        from_attributes = True # Enables Pydantic to read SQLAlchemy models


# --- 4. DATABASE DEPENDENCY ---
# This ensures each request gets its own DB connection session and closes it after the request is done.
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# --- 5. REFACTORED API ENDPOINTS ---

@app.get("/", response_model=list[TaskResponse])
def get_all_tasks(db: Session = Depends(get_db)):
    return db.query(DBTask).all()


@app.get("/tasks/{id}", response_model=TaskResponse)
def get_tasks_by_id(id: int, db: Session = Depends(get_db)):
    task = db.query(DBTask).filter(DBTask.id == id).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task Not Found")
    return task


@app.post("/tasks", response_model=TaskResponse)
def add_tasks(task: TaskCreate, db: Session = Depends(get_db)):
    db_task = DBTask(text=task.text, status=task.status, priority=task.priority)
    db.add(db_task)
    db.commit()
    db.refresh(db_task)  # Refreshes db_task to get the auto-generated ID from Postgres
    return db_task


@app.put("/task/{id}") # Fixed path parameter to match standard REST conventions
def update_task(id: int, updated_task: TaskCreate, db: Session = Depends(get_db)):
    db_task = db.query(DBTask).filter(DBTask.id == id).first()
    if not db_task:
        raise HTTPException(status_code=404, detail="No Match Found")
    db_task.text = updated_task.text
    db_task.status = updated_task.status
    db_task.priority = updated_task.priority
    
    db.commit()
    return {"message": "Task has been updated successfully!"}


@app.delete("/task/{id}") # Fixed path parameter to match standard REST conventions
def delete_task(id: int, db: Session = Depends(get_db)):
    db_task = db.query(DBTask).filter(DBTask.id == id).first()
    if not db_task:
        raise HTTPException(status_code=404, detail="Task Id not Found")
    
    db.delete(db_task)
    db.commit()
    return {"message": "Task has been deleted successfully!"}